# SPDX-License-Identifier: GPL-2.0-or-later

"""Texture-direction probe evidence used by the UV merge optimizer.

The probe itself can be generated by an external tool such as openSHIBIE and
projected/baked back into the mesh's current UV map. This module deliberately
keeps the interchange format independent from Blender so evidence can be
generated and validated outside Blender before it is imported.
"""

import json
import math


SCHEMA = "vuv-probe-evidence-v1"
OBJECT_PROPERTY = "vuv_probe_evidence"

_EDGE_FIELDS = (
    "merge_score",
    "confidence",
    "direction_delta_deg",
    "direction_score",
    "scale_ratio",
    "scale_score",
    "phase_error",
    "continuity_score",
    "flipped",
    "can_merge",
)


def edge_key(vertex_indices):
    """Return a stable key for an undirected mesh edge."""
    values = sorted(int(value) for value in vertex_indices)
    if len(values) != 2 or values[0] == values[1]:
        raise ValueError("An evidence edge must reference two distinct vertices")
    return "{}:{}".format(values[0], values[1])


def _edge_key_from_record(record):
    values = record.get("vertices", record.get("edge_vertices"))
    if values is None and "v1" in record and "v2" in record:
        values = (record["v1"], record["v2"])
    if values is None:
        raise ValueError("Probe evidence edge is missing vertices")
    return edge_key(values)


def _finite_float(value, default=None):
    try:
        value = float(value)
    except (TypeError, ValueError):
        return default
    return value if math.isfinite(value) else default


def _clamp01(value):
    return max(0.0, min(1.0, float(value)))


def _normalise_edge(record):
    if not isinstance(record, dict):
        raise ValueError("Each probe evidence edge must be an object")
    key = _edge_key_from_record(record)
    raw_values = record.get("vertices", record.get("edge_vertices"))
    if raw_values is None:
        raw_values = (record.get("v1"), record.get("v2"))
    values = sorted(int(value) for value in raw_values)
    if len(values) != 2:
        parts = [int(value) for value in key.split(":")]
        values = parts

    normalised = {"vertices": values}
    for field in _EDGE_FIELDS:
        if field not in record:
            continue
        if field in {"flipped", "can_merge"}:
            normalised[field] = bool(record[field])
        else:
            parsed = _finite_float(record[field])
            if parsed is not None:
                normalised[field] = parsed
    return key, normalised


def normalize_evidence(payload):
    """Validate and normalize a probe evidence payload.

    Accepted input:

    {
        "schema": "vuv-probe-evidence-v1",
        "object": "UV_Test_Model",
        "edges": [
            {
                "vertices": [12, 18],
                "merge_score": 0.92,
                "confidence": 0.95,
                "direction_delta_deg": 4.5,
                "scale_ratio": 1.02,
                "phase_error": 0.03,
                "flipped": false
            }
        ]
    }

    ``edges`` may also be a dictionary keyed by ``"min_vertex:max_vertex"``.
    """
    if not isinstance(payload, dict):
        raise ValueError("Probe evidence root must be a JSON object")
    schema = payload.get("schema", SCHEMA)
    if schema != SCHEMA:
        raise ValueError("Unsupported probe evidence schema: {}".format(schema))

    raw_edges = payload.get("edges", [])
    if isinstance(raw_edges, dict):
        records = []
        for key, value in raw_edges.items():
            if not isinstance(value, dict):
                raise ValueError("Probe evidence edge values must be objects")
            values = [int(part) for part in str(key).split(":")]
            value = dict(value)
            value.setdefault("vertices", values)
            records.append(value)
    elif isinstance(raw_edges, list):
        records = raw_edges
    else:
        raise ValueError("Probe evidence edges must be a list or object")

    edges = {}
    for record in records:
        key, normalised = _normalise_edge(record)
        edges[key] = normalised

    result = {
        "schema": SCHEMA,
        "object": str(payload.get("object", payload.get("object_name", ""))),
        "source": str(payload.get("source", "")),
        "edges": edges,
    }
    for field in ("generated_at", "probe_image", "notes"):
        if field in payload:
            result[field] = payload[field]
    return result


def encode_evidence(evidence):
    """Return normalized evidence as stable, human-readable JSON."""
    normalised = normalize_evidence(evidence)
    edges = []
    for key in sorted(normalised["edges"]):
        record = dict(normalised["edges"][key])
        edges.append(record)
    payload = dict(normalised)
    payload["edges"] = edges
    return json.dumps(payload, ensure_ascii=False, sort_keys=True, indent=2)


def load_stored_evidence(obj):
    """Read normalized evidence stored on a Blender object, if present."""
    raw = obj.get(OBJECT_PROPERTY)
    if not raw:
        return None
    if isinstance(raw, dict):
        return normalize_evidence(raw)
    try:
        return normalize_evidence(json.loads(str(raw)))
    except (TypeError, ValueError, json.JSONDecodeError):
        return None


def _metric_score(entry):
    direct = _finite_float(entry.get("merge_score"))
    if direct is not None:
        return _clamp01(direct)

    components = []
    direction_score = _finite_float(entry.get("direction_score"))
    if direction_score is None:
        delta = _finite_float(entry.get("direction_delta_deg"))
        if delta is not None:
            direction_score = 1.0 - min(abs(delta) / 45.0, 1.0)
    if direction_score is not None:
        components.append(_clamp01(direction_score))

    scale_score = _finite_float(entry.get("scale_score"))
    if scale_score is None:
        ratio = _finite_float(entry.get("scale_ratio"))
        if ratio is not None and ratio > 0.0:
            scale_score = 1.0 - min(
                abs(math.log(ratio)) / math.log(2.5), 1.0)
    if scale_score is not None:
        components.append(_clamp01(scale_score))

    continuity_score = _finite_float(entry.get("continuity_score"))
    if continuity_score is None:
        phase_error = _finite_float(entry.get("phase_error"))
        if phase_error is not None:
            continuity_score = 1.0 - min(abs(phase_error), 1.0)
    if continuity_score is not None:
        components.append(_clamp01(continuity_score))

    if not components:
        return None
    return sum(components) / len(components)


def summarize_boundary(
    boundary,
    evidence,
    min_confidence=0.0,
    reject_flipped=True,
):
    """Summarize probe evidence for a chart boundary.

    ``boundary`` is an iterable of BMesh edges. The return value is always a
    dictionary so callers can report unsupported, accepted, and rejected
    boundaries uniformly.
    """
    summary = {
        "supported": False,
        "score": 0.0,
        "confidence": 0.0,
        "coverage": 0.0,
        "hard_reject": False,
        "reason": "NO_EVIDENCE",
        "edges": [],
    }
    if not evidence or not evidence.get("edges"):
        return summary

    boundary = list(boundary)
    records = []
    for edge in boundary:
        key = edge_key(vertex.index for vertex in edge.verts)
        record = evidence["edges"].get(key)
        if record is None:
            continue
        confidence = _finite_float(record.get("confidence"), 1.0)
        confidence = _clamp01(confidence)
        edge_summary = {
            "edge": key,
            "confidence": confidence,
            "score": _metric_score(record),
            "flipped": bool(record.get("flipped", False)),
            "can_merge": record.get("can_merge"),
        }
        summary["edges"].append(edge_summary)
        if confidence < min_confidence:
            continue
        if record.get("can_merge") is False:
            summary["hard_reject"] = True
        if reject_flipped and record.get("flipped", False):
            summary["hard_reject"] = True
        if edge_summary["score"] is not None:
            records.append(edge_summary)

    if not summary["edges"]:
        return summary

    summary["supported"] = True
    summary["coverage"] = len(summary["edges"]) / max(len(boundary), 1)
    if records:
        weights = [max(item["confidence"], 1e-6) for item in records]
        summary["score"] = sum(
            item["score"] * weight for item, weight in zip(records, weights)
        ) / sum(weights)
        summary["confidence"] = sum(weights) / len(weights)
        summary["reason"] = (
            "REJECTED_PROBE" if summary["hard_reject"] else "PROBE_SUPPORTED")
    else:
        summary["reason"] = "LOW_CONFIDENCE"
    return summary
